In [1]:
import pandas as pd
from dateutil.relativedelta import relativedelta

### 데이터 로드

In [2]:
df = pd.read_csv("..\\..\\data\\연도별 재무.csv", encoding = "ms949")

### 매출액은 연결과 개별을 구분지어 필터생성할 것이기 때문에 구분해준다

In [3]:
A = df[(df["Kind"] == "NFS-IFRS(C)") & (df["Item Name "] == "매출액(천원)")]
df.loc[A.index, "Item Name "] = "매출액(연결)"

In [4]:
df.head()

,Symbol,Kind,Item Name,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-01-31
0,A005930,NFS-IFRS(C),매출액(연결),"206,205,987,000","200,653,482,000","201,866,745,000","239,575,376,000","243,771,415,000",NaN,NaN
1,A005930,NFS-IFRS(S),매출액(천원),"137,825,547,000","135,205,045,000","133,947,204,000","161,915,007,000","170,381,870,000",NaN,NaN
2,A005930,NFS-IFRS(C),영업이익(천원),"25,025,071,000","26,413,442,000","29,240,672,000","53,645,038,000","58,886,669,000",NaN,NaN
3,A005930,NFS-IFRS(C),지배주주순이익(천원),"23,082,499,000","18,694,628,000","22,415,655,000","41,344,569,000","43,890,877,000",NaN,NaN
4,A005930,NFS-IFRS(C),총자본(천원),"168,088,188,000","179,059,805,000","192,963,033,000","214,491,428,000","247,753,177,000",NaN,NaN

### 데이터의 계정이름을 사용하기 쉬운 계정이름으로 변환

In [5]:
계정명 = df["Item Name "].drop_duplicates().tolist()

In [6]:
바꿀계정명 = ["연결매출","매출액", "영업이익", "지배주주순이익", "총자본", "총부채", "자본금", "이익잉여금", 
                 "영업활동으로인한현금흐름", "투자활동으로인한현금흐름", "배당", "주가", "종가", "상장주식수"]

In [7]:
temp = {}

for 계정 in range(len(계정명)):
    temp[계정명[계정]] = 바꿀계정명[계정]
    print(계정명[계정]+ "     ->     " +  바꿀계정명[계정])

매출액(연결)     ->     연결매출
매출액(천원)     ->     매출액
영업이익(천원)     ->     영업이익
지배주주순이익(천원)     ->     지배주주순이익
총자본(천원)     ->     총자본
총부채(천원)     ->     총부채
자본금(천원)     ->     자본금
이익잉여금(천원)     ->     이익잉여금
영업활동으로인한현금흐름(천원)     ->     영업활동으로인한현금흐름
투자활동으로인한현금흐름(천원)     ->     투자활동으로인한현금흐름
수정DPS(보통주,현금)(원)     ->     배당
수정주가(원)     ->     주가
종가(원)     ->     종가
상장주식수(주)     ->     상장주식수

### 바뀐 계정 할당

In [8]:
df = df.replace({"Item Name ": temp})

In [9]:
# 연결매출 판별하는데 사용한 Kind는 이제 필요가 없으므로 drop한다

In [10]:
df = df.drop("Kind", axis=1)

In [11]:
df.head()

,Symbol,Item Name,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-01-31
0,A005930,연결매출,"206,205,987,000","200,653,482,000","201,866,745,000","239,575,376,000","243,771,415,000",NaN,NaN
1,A005930,매출액,"137,825,547,000","135,205,045,000","133,947,204,000","161,915,007,000","170,381,870,000",NaN,NaN
2,A005930,영업이익,"25,025,071,000","26,413,442,000","29,240,672,000","53,645,038,000","58,886,669,000",NaN,NaN
3,A005930,지배주주순이익,"23,082,499,000","18,694,628,000","22,415,655,000","41,344,569,000","43,890,877,000",NaN,NaN
4,A005930,총자본,"168,088,188,000","179,059,805,000","192,963,033,000","214,491,428,000","247,753,177,000",NaN,NaN

In [12]:
# df 시간변환

In [13]:
df = df.set_index(['Symbol', "Item Name "])
시간변환 = pd.to_datetime(df.columns)
시간변환 = 시간변환.strftime("%Y-%m-%d")
시간변환 = 시간변환.rename("date")
df.columns = pd.to_datetime(시간변환)

In [14]:
df.head()

date                     2014-12-31       2015-12-31       2016-12-31  \
Symbol  Item Name
A005930 연결매출        206,205,987,000  200,653,482,000  201,866,745,000
        매출액         137,825,547,000  135,205,045,000  133,947,204,000
        영업이익         25,025,071,000   26,413,442,000   29,240,672,000
        지배주주순이익      23,082,499,000   18,694,628,000   22,415,655,000
        총자본         168,088,188,000  179,059,805,000  192,963,033,000

date                     2017-12-31       2018-12-31 2019-12-31 2020-01-31
Symbol  Item Name
A005930 연결매출        239,575,376,000  243,771,415,000        NaN        NaN
        매출액         161,915,007,000  170,381,870,000        NaN        NaN
        영업이익         53,645,038,000   58,886,669,000        NaN        NaN
        지배주주순이익      41,344,569,000   43,890,877,000        NaN        NaN
        총자본         214,491,428,000  247,753,177,000        NaN        NaN

### 인덱스를 회사 - 시간의 이중 인덱스 변경. 컬럼은 재무 지표들로 변경

In [15]:
df = df.stack().swaplevel().unstack()

### df type 실수로 변환

In [16]:
for 계정 in df.columns:
    df[계정] = df[계정].str.replace(',', "")

df = df.astype(float)

In [17]:
# 데이터들의 년도를 미뤄주는 함수. 예를 들어 lag_year가 1년이면 1년전의 데이터를 가져오겠다는 뜻!! 한번 실행해보길
def lag_year(df, lag_year):
    copy_df = df.copy()
    lagged_df = copy_df.shift(lag_year)
    lag_index_list = []
    for index in df.columns:
        lag_index = index + " " + str(lag_year) + "Y lag"
        lag_index_list.append(lag_index)
    
    lagged_df.columns = lag_index_list
    
    return lagged_df

In [18]:
# 3월 15일을 기준으로 사용할 수 있는 재무데이터의 년도가 다름. 3월 전에는 전전년도의 재무데이터를 사용가능하지만
# 4월부터는 전년도 재무데이터를 사용할 수 있음
# 마찬가지로 이해가 안 된다면 실행시켜보길 권함!

# 당겨오는 함수
def assign_announcement_year(df):
    copy_df = df.copy()
    
    # df 의 시간을 거슬러 올라가면서
    for time in reversed(copy_df.index):

        month = time.month
        day = time.day
        
        try:
            
            # 만약 해당 월이 4월 이상이라면
            # 작년 12월 데이터를 카피한다 -- 작년에 대한 공시가 나와있기 때문
            if month >= 4:
                ref_time = time- relativedelta(years = 1) 
                copy_df.loc[time] = copy_df.loc[ref_time]

                
            else:
                # 재작년 12월의 데이터를 카피한다
                # 작년 공시가 나와있지 않기 때문
                ref_time = time- relativedelta(years = 1) - relativedelta(months = month-1) - relativedelta(days = day) 
                copy_df.loc[time] = copy_df.loc[ref_time]                

        except Exception as e:
            copy_df.loc[time] = None
            pass
    
    return copy_df

In [ ]:
### ROE, 영업이익률 생성 -- 여기서 생성해주는 이유는 추후 몇년단위의 증가폭을 보고 싶은데, 기본 df의
### 지표에 설정되어 있지 않기 때문에 미리 생성하지 않으면 lag_year로 과거 데이터들을 가져오기 힘들기 때문

In [27]:
df["ROE"] = df["지배주주순이익"] /  df["총자본"]
df["영업이익률"] = df["영업이익"] / df["매출액"]

In [28]:
# Sample Test

In [29]:
주식데이터 = ["종가", "주가", "상장주식수"]

In [35]:
company = 'A005930'
## 이 부분이 복잡해보이는데 복사해서 밖으로 빼서 별도의 셀에서 한 행씩 실행시켜보면 이해가 됨

 # 회사의 데이터를 가져와서
temp = df.loc[company] 
# 즉시 알 수 있는 주식 데이터들만을 뽑아온 후
stock_temp = temp[주식데이터]
financial_temp = temp[temp.columns[~temp.columns.isin(주식데이터)]]

# 전년도에 대한 감사보고서 제출일이 3월 15일 이므로 3월을 기준으로 이전이라면 2년전의 데이터, 이후라면 1년전의 데이터 사용
# 필터 조건을 위한 전년도 데이터들을 생성하고
lag_1Y = lag_year(financial_temp, 1)
lag_2Y = lag_year(financial_temp, 2)
lag_3Y = lag_year(financial_temp, 3)
lag_4Y = lag_year(financial_temp, 4)

# 이를 합친다
financial_temp = pd.concat([financial_temp, lag_1Y, lag_2Y, lag_3Y, lag_4Y], axis = 1)
financial_temp = assign_announcement_year(financial_temp)

# stock index도 최신으로 업데이트 해 준다.
temp = financial_temp.join(stock_temp)

### 왜곡이 일어나지 않는 이유. 
# 해당 데이터들의 lag까지 가져왔기 때문임

temp["영업이익률"] = temp["영업이익"] / temp["매출액"]
temp["매출액 100억 이상"] = temp["매출액"] > 10000000
temp["영업이익률 3년동안 증가"] = (temp["영업이익률"] > temp["영업이익률 1Y lag"]) &  (temp["영업이익률"] > temp["영업이익률 2Y lag"]) &  (temp["영업이익률 1Y lag"] > temp["영업이익률 2Y lag"])

temp["시가총액"] = temp["상장주식수"] * temp["종가"]
temp["영업이익시총비율"] = (temp["영업이익"] / temp["시가총액"])


# temp를 밖에서 빼서 한번씩 실행하면 이해가 될거임!

In [38]:
temp[["시가총액", "영업이익률", "영업이익률 1Y lag", "영업이익률 3년동안 증가"]]

                    시가총액     영업이익률  영업이익률 1Y lag  영업이익률 3년동안 증가
date
2014-12-31  1.954662e+14       NaN           NaN          False
2015-12-31  1.855972e+14  0.181571           NaN          False
2016-12-31  2.535042e+14  0.195358      0.181571          False
2017-12-31  3.289430e+14  0.218300      0.195358           True
2018-12-31  2.310306e+14  0.331316      0.218300           True
2019-12-31  3.331139e+14  0.345616      0.331316           True
2020-01-31  3.366957e+14  0.345616      0.331316           True

In [34]:
# temp의 모양을 살펴보면 위와 같음.
# 주가데이터들은 현재값들이 잘 들어가있고, 그 밖에 재무데이터들은 해당 시점에 알 수 있는 가장 최신의 값들이 
# 잘 들어간 모습을 확인할 수 있음

## 필터링 조건 생성부

In [ ]:
주식데이터 = ["종가", "주가", "상장주식수"]

# 회사 리스트
company_list = df.index.levels[0]

In [39]:
new_data = []
for company in company_list:
    ## 이 부분이 복잡해보이는데 복사해서 밖으로 빼서 별도의 셀에서 한 행씩 실행시켜보면 이해가 됨
    temp = df.loc[company] 
    
    # 즉시 알 수 있는 주식 데이터와 재무데이터로 구분한다 
    stock_temp = temp[주식데이터]
    financial_temp = temp[temp.columns[~temp.columns.isin(주식데이터)]]
    
    # 필터 조건을 위한 전년도 데이터들을 생성하고 -- 재무데이터에 한정
    lag_1Y = lag_year(financial_temp, 1)
    lag_2Y = lag_year(financial_temp, 2)
    lag_3Y = lag_year(financial_temp, 3)
    lag_4Y = lag_year(financial_temp, 4)

    # 이를 재무데이터에 합친다
    financial_temp = pd.concat([financial_temp, lag_1Y, lag_2Y, lag_3Y, lag_4Y], axis = 1)
    
    # assign_announcement_year함수는 lag까지 해당 시점으로 가져오기 때문에 발표가 나기 전 시점(1~3월까지에도)
    # 왜곡이 일어나지 않는다.
    financial_temp = assign_announcement_year(financial_temp)

    # 당겨진 재무데이터에 주식 데이터를 합병하여 해당 시점에 알 수 있는 가장 최근의 정보들의 데이터프레임을 만든다.
    temp = financial_temp.join(stock_temp)
    
    
    # 주식데이터 사용하는 것들
    temp["시가총액"] = temp["상장주식수"] * temp["종가"]
    
    # 포괄손익계산서
    # 매출액 단위(천원)
    temp["매출액 100억 이상"] = temp["매출액"] > 10000000
    
    #영업이익 3개년 모두 0 이상
    temp["영업이익 3년동안 0 이상"] = (temp["영업이익"] > 0) & (temp["영업이익 1Y lag"] > 0) & (temp["영업이익 2Y lag"] > 0)
    
    # 영업이익률 & 증가
    temp["영업이익률"] = temp["영업이익"] / temp["매출액"]
    temp["영업이익률 3년동안 증가"] = (temp["영업이익률"] > temp["영업이익률 1Y lag"]) &  (temp["영업이익률"] > temp["영업이익률 2Y lag"]) &  (temp["영업이익률 1Y lag"] > temp["영업이익률 2Y lag"])
    
    # 매출액 3년 동안 증가
    temp["매출액 3년동안 증가"] = (temp["매출액"] > temp["매출액 1Y lag"]) &  (temp["매출액"] > temp["매출액 2Y lag"]) &  (temp["매출액 1Y lag"] > temp["매출액 2Y lag"])
    
    # 시가총액 비율
    # 이런 식으로 재무데이터와 주가 데이터가 혼합
    temp["순이익시총비율 0.1이상"] = (temp["지배주주순이익"] / temp["시가총액"])  > 0.1
    temp["영업이익시총비율 0.1이상"] = (temp["영업이익"] / temp["시가총액"]) > 0.1
    
    
    ## 재무상태표
    # 자본잠식
    temp["자본잠식 없음"] = temp["총자본"] > 0
    
    # 부채비율
    temp["부채비율"] = temp["총부채"] / temp["총자본"]
    temp["부채비율 150% 이하"] = temp["부채비율"] < 1.5
  
    # 자본금
    temp["자본금 증가율"] = (temp["자본금"] - temp["자본금 1Y lag"]) / temp["자본금 1Y lag"]
    temp["자본금 변동없음"] = temp["자본금 증가율"].abs() < 0.05
    
    # 이익잉여금
    
    temp["이익잉여금이 3년동안 증가"] = (temp["이익잉여금"] > temp["이익잉여금 1Y lag"]) &  (temp["이익잉여금"] > temp["이익잉여금 2Y lag"]) &  (temp["이익잉여금 1Y lag"] > temp["이익잉여금 2Y lag"])

    
    ## 현금흐름표
    
    # 영업활동현금흐름
    temp["영업활동으로인한현금흐름 판별"] = temp["영업활동으로인한현금흐름"] > 0
    temp["3년 중 2년 이상 영업활동으로인한현금흐름 0 초과"] = (temp["영업활동으로인한현금흐름 판별"].rolling(3).sum() > 2)
    
    # 투자활동현금흐름
    temp["투자활동으로인한현금흐름 판별"] = temp["투자활동으로인한현금흐름"] < 0
    temp["3년 중 2년 이상 투자활동으로인한현금흐름 0 미만"] = (temp["투자활동으로인한현금흐름 판별"].rolling(3).sum() > 2)
    
    ## 배당
    temp["배당존재"] = temp["배당"] > 0 
    temp["배당이 3년동안 증가"] =(temp["배당"] > temp["배당 1Y lag"]) &  (temp["배당"] > temp["배당 2Y lag"]) &  (temp["배당 1Y lag"] > temp["배당 2Y lag"])

    ## 기타
    # ROE가 5% 이상(수익성)
    temp["ROE"] = temp["지배주주순이익"] / temp["총자본"]
    temp["ROE 5퍼 이상"]  = temp["ROE"] > 0.05
    
    # 추후 많은 지표들 추가
    
    
    # 정리부분
    temp["Symbol"] = company
    temp = temp.reset_index()
    temp = temp.set_index(["Symbol", "date"])
    
    new_data.append(temp)

In [40]:
old = pd.DataFrame()
for company_data in new_data:
    old = pd.concat([old, company_data])

In [41]:
필터조건 = ["매출액 100억 이상", "영업이익 3년동안 0 이상", "영업이익률 3년동안 증가", "매출액 3년동안 증가", "순이익시총비율 0.1이상", 
        "영업이익시총비율 0.1이상","자본잠식 없음", "부채비율 150% 이하", "자본금 변동없음", 
        "이익잉여금이 3년동안 증가","3년 중 2년 이상 영업활동으로인한현금흐름 0 초과",
        "3년 중 2년 이상 투자활동으로인한현금흐름 0 미만","배당존재", "배당이 3년동안 증가","ROE 5퍼 이상"]

In [42]:
년도별조건 = old[필터조건]

In [43]:
년도별조건

                    매출액 100억 이상  영업이익 3년동안 0 이상  영업이익률 3년동안 증가  매출액 3년동안 증가  \
Symbol  date
A005930 2014-12-31        False           False          False        False
        2015-12-31         True           False          False        False
        2016-12-31         True           False          False        False
        2017-12-31         True            True           True        False
        2018-12-31         True            True           True        False
        2019-12-31         True            True           True         True
        2020-01-31         True            True           True         True
A000660 2014-12-31        False           False          False        False
        2015-12-31         True           False          False        False
        2016-12-31         True           False          False        False
        2017-12-31         True            True          False        False
        2018-12-31         True            True          False        False
        2019-12-31         True            True           True         True
        2020-01-31         True            True           True         True
A207940 2014-12-31        False           False          False        False
        2015-12-31         True           False          False        False
        2016-12-31         True           False          False        False
        2017-12-31         True           False          False        False
        2018-12-31         True           False           True         True
        2019-12-31         True           False          False         True
        2020-01-31         True           False          False         True
A035420 2014-12-31        False           False          False        False
        2015-12-31         True           False          False        False
        2016-12-31         True           False          False        False
        2017-12-31         True            True          False         True
        2018-12-31         True            True          False         True
        2019-12-31         True            True          False         True
        2020-01-31         True            True          False         True
A005380 2014-12-31        False           False          False        False
        2015-12-31         True           False          False        False
...                         ...             ...            ...          ...
A274090 2017-12-31        False           False          False        False
        2018-12-31        False           False          False        False
A294140 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
        2017-12-31        False           False           True         True
        2018-12-31         True           False           True         True
A294630 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
        2017-12-31        False           False          False        False
        2018-12-31        False           False          False        False
A900050 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
A900090 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
        2017-12-31        False            True          False        False
        2018-12-31        False           False          False        False
A900130 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
        2017-12-31        False           False          False        False
        2018-12-31        False           False          False        False
A900180 2014-12-31        False           False          False        False
        2015-12-31        False           False          False        False
        2016-12-31        False           False          False        False
        2017-12-31        False            True          False        False
A950010 2014-12-31        False           False          False        False

                    순이익시총비율 0.1이상  영업이익시총비율 0.1이상  자본잠식 없음  부채비율 150% 이하  \
Symbol  date
A005930 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
        2018-12-31          False           False     True          True
        2019-12-31          False           False     True          True
        2020-01-31          False           False     True          True
A000660 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
        2018-12-31          False           False     True          True
        2019-12-31          False           False     True          True
        2020-01-31          False           False     True          True
A207940 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
        2018-12-31          False           False     True          True
        2019-12-31          False           False     True          True
        2020-01-31          False           False     True          True
A035420 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
        2018-12-31          False           False     True          True
        2019-12-31          False           False     True          True
        2020-01-31          False           False     True          True
A005380 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
...                           ...             ...      ...           ...
A274090 2017-12-31          False           False     True         False
        2018-12-31          False           False     True          True
A294140 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True         False
        2017-12-31          False           False    False          True
        2018-12-31          False           False     True         False
A294630 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False    False          True
        2018-12-31          False           False     True          True
A900050 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
A900090 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
        2018-12-31          False           False     True          True
A900130 2014-12-31          False           False    False         False
        2015-12-31          False           False     True         False
        2016-12-31          False           False     True         False
        2017-12-31          False           False     True         False
        2018-12-31          False           False     True         False
A900180 2014-12-31          False           False    False         False
        2015-12-31          False           False     True          True
        2016-12-31          False           False     True          True
        2017-12-31          False           False     True          True
A950010 2014-12-31          False           False    False         False

                    자본금 변동없음  이익잉여금이 3년동안 증가  3년 중 2년 이상 영업활동으로인한현금흐름 0 초과  \
Symbol  date
A005930 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True            True                          True
        2018-12-31      True            True                          True
        2019-12-31      True            True                          True
        2020-01-31      True            True                          True
A000660 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True            True                          True
        2018-12-31      True            True                          True
        2019-12-31      True            True                          True
        2020-01-31      True            True                          True
A207940 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31     False           False                         False
        2017-12-31     False           False                         False
        2018-12-31      True           False                         False
        2019-12-31      True           False                         False
        2020-01-31      True           False                         False
A035420 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True            True                          True
        2018-12-31      True            True                          True
        2019-12-31      True            True                          True
        2020-01-31      True            True                          True
A005380 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
...                      ...             ...                           ...
A274090 2017-12-31     False           False                         False
        2018-12-31     False           False                         False
A294140 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True           False                         False
        2018-12-31      True           False                         False
A294630 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True           False                         False
        2018-12-31     False           False                         False
A900050 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31     False           False                         False
A900090 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True            True                         False
        2018-12-31     False           False                          True
A900130 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31      True           False                          True
        2018-12-31     False           False                          True
A900180 2014-12-31     False           False                         False
        2015-12-31     False           False                         False
        2016-12-31      True           False                         False
        2017-12-31     False            True                          True
A950010 2014-12-31     False           False                         False

                    3년 중 2년 이상 투자활동으로인한현금흐름 0 미만   배당존재  배당이 3년동안 증가  \
Symbol  date
A005930 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-31                          True   True         True
A000660 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-31                          True   True         True
A207940 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                         False  False        False
        2019-12-31                         False  False        False
        2020-01-31                         False  False        False
A035420 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-31                          True   True         True
A005380 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
...                                          ...    ...          ...
A274090 2017-12-31                         False  False        False
        2018-12-31                          True  False        False
A294140 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                         False  False        False
        2018-12-31                         False  False        False
A294630 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                          True  False        False
A900050 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
A900090 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                         False  False        False
        2018-12-31                         False  False        False
A900130 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                          True  False        False
A900180 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
A950010 2014-12-31                         False  False        False

                    ROE 5퍼 이상
Symbol  date
A005930 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-31       True
A000660 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-31       True
A207940 2014-12-31      False
        2015-12-31      False
        2016-12-31       True
        2017-12-31      False
        2018-12-31      False
        2019-12-31       True
        2020-01-31       True
A035420 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-31       True
A005380 2014-12-31      False
        2015-12-31       True
...                       ...
A274090 2017-12-31      False
        2018-12-31      False
A294140 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31       True
        2018-12-31       True
A294630 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31       True
        2018-12-31      False
A900050 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
A900090 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31      False
A900130 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31      False
        2018-12-31       True
A900180 2014-12-31      False

In [44]:
년도별조건.to_csv("year_filter.csv", encoding = "ms949")