In [1]:
import pandas as pd

# 데이터를 불러온다

In [135]:
df = pd.read_csv("..\\..\\data\\donghyojaechul_yearly_financial_5years.csv", encoding = "ms949")

# 데이터의 계정이름을 사용하기 쉬운 계정이름으로 변환

In [136]:
계정명 = df["Item Name "].drop_duplicates().tolist()

In [137]:
바꿀계정명 = ["매출액", "영업이익", "지배주주순이익", "총자본", "총부채", "자본금", "이익잉여금", 
                 "영업활동으로인한현금흐름", "투자활동으로인한현금흐름", "배당", "주가", "상장주식수"]

In [138]:
temp = {}

for 계정 in range(len(계정명)):
    temp[계정명[계정]] = 바꿀계정명[계정]
    print(계정명[계정]+ "     ->     " +  바꿀계정명[계정])

매출액(원)     ->     매출액
영업이익(원)     ->     영업이익
지배주주순이익(원)     ->     지배주주순이익
총자본(원)     ->     총자본
총부채(원)     ->     총부채
자본금(원)     ->     자본금
이익잉여금(원)     ->     이익잉여금
영업활동으로인한현금흐름(원)     ->     영업활동으로인한현금흐름
투자활동으로인한현금흐름(원)     ->     투자활동으로인한현금흐름
수정DPS(보통주,현금)(원)     ->     배당
수정주가(원)     ->     주가
상장주식수 (보통+우선)(주)     ->     상장주식수

### 바뀐 계정 할당

In [139]:
df = df.replace({"Item Name ": temp})

### df타입을 실수로 변환

In [140]:
### 컬럼의 2014-12-31 string 포맷을 datetime 포맷으로 바꾼 후 데이터프레임을 회사명과 시간의 이중 인덱스로 바꿔줌

In [141]:
df = df.set_index(['Symbol', "Item Name "])
시간변환 = pd.to_datetime(df.columns)

시간변환 = 시간변환.strftime("%Y-%m-%d")
시간변환 = 시간변환.rename("date")
df.columns = pd.to_datetime(시간변환)
df = df.stack().swaplevel().unstack()

In [142]:
df

Item Name                           매출액        배당          상장주식수  \
Symbol  date
A005930 2014-12-31  137,825,547,000,000    400.00    170,132,764
        2015-12-31  135,205,045,000,000    420.00    170,132,764
        2016-12-31  133,947,204,000,000    570.00    161,192,764
        2017-12-31  161,915,007,000,000    850.00    147,349,074
        2018-12-31  170,381,870,000,000  1,416.00  6,792,669,250
        2019-12-31                  NaN       NaN  6,792,669,250
        2020-01-28                  NaN       NaN  6,792,669,250
A000660 2014-12-31   16,893,716,000,000    300.00    728,002,365
        2015-12-31   18,780,792,000,000    500.00    728,002,365
        2016-12-31   16,733,111,000,000    600.00    728,002,365
        2017-12-31   29,718,939,000,000  1,000.00    728,002,365
        2018-12-31   40,324,651,000,000  1,500.00    728,002,365
        2019-12-31                  NaN       NaN    728,002,365
        2020-01-28                  NaN       NaN    728,002,365
A207940 2014-12-31      105,148,783,570       NaN            NaN
        2015-12-31       91,278,028,790       NaN            NaN
        2016-12-31      294,622,020,770       NaN     66,165,000
        2017-12-31      464,629,334,140       NaN     66,165,000
        2018-12-31      535,805,801,070       NaN     66,165,000
        2019-12-31                  NaN       NaN     66,165,000
        2020-01-28                  NaN       NaN     66,165,000
A035420 2014-12-31    1,637,164,959,000    156.40     32,962,679
        2015-12-31    2,141,274,744,000    220.00     32,962,679
        2016-12-31    2,496,498,317,220    226.20     32,962,679
        2017-12-31    2,930,661,324,860    289.20     32,962,679
        2018-12-31    3,459,014,042,550    314.00    164,813,395
        2019-12-31                  NaN       NaN    164,813,395
        2020-01-28                  NaN       NaN    164,813,395
A005380 2014-12-31   43,045,875,000,000  3,000.00    285,478,625
        2015-12-31   44,439,694,000,000  4,000.00    285,478,625
...                                 ...       ...            ...
A274090 2017-12-31        6,977,238,000       NaN            NaN
        2018-12-31       12,703,258,000       NaN            NaN
A294140 2014-12-31          272,326,580       NaN            NaN
        2015-12-31        1,720,327,000       NaN            NaN
        2016-12-31        1,919,792,620       NaN            NaN
        2017-12-31       40,329,366,330       NaN            NaN
        2018-12-31       31,437,598,090       NaN            NaN
A294630 2014-12-31        5,315,997,000       NaN            NaN
        2015-12-31        3,915,593,000       NaN            NaN
        2016-12-31        1,427,908,520       NaN            NaN
        2017-12-31        4,963,563,020       NaN            NaN
        2018-12-31        4,854,015,300       NaN            NaN
A900050 2014-12-31                  NaN       NaN     83,129,535
        2015-12-31                  NaN       NaN     96,359,369
        2016-12-31                  NaN       NaN     97,859,369
A900090 2014-12-31                  NaN       NaN     54,000,000
        2015-12-31                  NaN       NaN     54,000,000
        2016-12-31                  NaN       NaN     54,000,000
        2017-12-31                  NaN       NaN     94,000,000
        2018-12-31                  NaN       NaN     94,000,000
A900130 2014-12-31                  NaN       NaN     55,880,000
        2015-12-31                  NaN       NaN     55,880,000
        2016-12-31                  NaN       NaN     55,880,000
        2017-12-31                  NaN       NaN            NaN
        2018-12-31                  NaN       NaN            NaN
A900180 2014-12-31                  NaN       NaN     90,088,249
        2015-12-31                  NaN       NaN     90,088,249
        2016-12-31                  NaN       NaN    102,507,511
        2017-12-31                  NaN       NaN    107,630,204
A950010 2014-12-31                  NaN       NaN      4,803,497

Item Name                         영업이익        영업활동으로인한현금흐름  \
Symbol  date
A005930 2014-12-31  25,025,071,000,000  36,975,389,000,000
        2015-12-31  26,413,442,000,000  40,061,761,000,000
        2016-12-31  29,240,672,000,000  47,385,644,000,000
        2017-12-31  53,645,038,000,000  62,162,041,000,000
        2018-12-31  58,886,669,000,000  67,031,863,000,000
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A000660 2014-12-31   5,109,466,000,000   5,866,691,000,000
        2015-12-31   5,336,100,000,000   9,319,520,000,000
        2016-12-31   3,276,746,000,000   5,548,922,000,000
        2017-12-31  13,721,326,000,000  14,690,614,000,000
        2018-12-31  20,843,750,000,000  22,227,199,000,000
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A207940 2014-12-31    -105,197,235,010    -163,664,339,170
        2015-12-31    -203,642,443,710    -265,513,751,570
        2016-12-31     -30,422,638,580     -62,661,298,030
        2017-12-31      65,979,402,410     149,816,327,600
        2018-12-31      55,678,744,520     -32,417,327,330
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A035420 2014-12-31     758,199,066,000     836,558,093,000
        2015-12-31     830,224,960,870     851,367,412,450
        2016-12-31   1,102,040,475,790   1,164,024,257,900
        2017-12-31   1,179,187,806,330     939,981,997,690
        2018-12-31     942,532,561,550     973,506,368,150
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A005380 2014-12-31   7,549,986,000,000   2,120,845,000,000
        2015-12-31   6,357,906,000,000   1,248,415,000,000
...                                ...                 ...
A274090 2017-12-31        -648,452,000      -1,264,039,000
        2018-12-31        -916,230,000      -8,979,501,000
A294140 2014-12-31      -6,343,291,200      -5,661,881,820
        2015-12-31      -6,059,759,130      -5,072,031,820
        2016-12-31      -5,137,104,060      -3,120,555,920
        2017-12-31       6,652,781,330       4,754,597,880
        2018-12-31        -319,511,420       2,355,722,640
A294630 2014-12-31        -498,000,000         189,910,000
        2015-12-31        -574,557,000       1,700,356,000
        2016-12-31      -3,058,089,000      -4,252,321,000
        2017-12-31      -1,357,815,050      -1,666,684,000
        2018-12-31      -1,604,857,700      -2,508,735,020
A900050 2014-12-31    -102,550,556,000     -43,578,948,000
        2015-12-31     -17,280,290,000     -28,404,533,000
        2016-12-31    -158,037,404,000      51,796,583,000
A900090 2014-12-31      26,674,076,000      -1,223,124,000
        2015-12-31      30,359,762,000       7,153,429,000
        2016-12-31      36,574,307,000      37,802,300,000
        2017-12-31     -76,982,174,000       8,401,389,000
        2018-12-31                 NaN                 NaN
A900130 2014-12-31      -5,096,826,000      12,816,742,000
        2015-12-31      -1,018,239,000      19,110,676,000
        2016-12-31      -4,120,374,000      16,431,285,000
        2017-12-31       5,209,513,000       4,487,283,000
        2018-12-31       2,727,130,000      -8,253,397,000
A900180 2014-12-31      56,664,922,000      37,733,247,000
        2015-12-31      59,431,509,000      55,591,016,000
        2016-12-31      48,937,537,000      51,811,131,000
        2017-12-31      31,359,871,000      29,846,048,000
A950010 2014-12-31      17,000,861,000      38,192,401,000

Item Name                         이익잉여금                자본금       주가  \
Symbol  date
A005930 2014-12-31  169,529,604,000,000    897,514,000,000   26,540
        2015-12-31  185,132,014,000,000    897,514,000,000   25,200
        2016-12-31  193,086,317,000,000    897,514,000,000   36,040
        2017-12-31  215,811,200,000,000    897,514,000,000   50,960
        2018-12-31  242,698,956,000,000    897,514,000,000   38,700
        2019-12-31                  NaN                NaN   55,800
        2020-01-28                  NaN                NaN   58,800
A000660 2014-12-31   10,276,904,000,000  3,657,652,000,000   47,750
        2015-12-31   14,358,988,000,000  3,657,652,000,000   30,750
        2016-12-31   17,066,583,000,000  3,657,652,000,000   44,700
        2017-12-31   27,287,256,000,000  3,657,652,000,000   76,500
        2018-12-31   42,033,601,000,000  3,657,652,000,000   60,500
        2019-12-31                  NaN                NaN   94,100
        2020-01-28                  NaN                NaN   96,300
A207940 2014-12-31     -287,359,112,360    101,833,245,000      NaN
        2015-12-31    1,601,530,282,540    137,843,605,000      NaN
        2016-12-31    1,424,706,873,010    165,412,500,000  151,000
        2017-12-31    1,327,734,757,200    165,412,500,000  371,000
        2018-12-31    1,509,718,830,210    165,412,500,000  386,500
        2019-12-31                  NaN                NaN  433,000
        2020-01-28                  NaN                NaN  494,000
A035420 2014-12-31    2,583,591,599,000     16,481,340,000  142,602
        2015-12-31    3,069,369,884,000     16,481,339,500  131,787
        2016-12-31    3,810,189,403,600     16,481,339,500  155,220
        2017-12-31    4,555,517,868,320     16,481,339,500  174,247
        2018-12-31    5,229,202,813,050     16,481,339,500  122,000
        2019-12-31                  NaN                NaN  186,500
        2020-01-28                  NaN                NaN  178,500
A005380 2014-12-31   54,649,863,000,000  1,488,993,000,000  169,000
        2015-12-31   60,035,088,000,000  1,488,993,000,000  149,000
...                                 ...                ...      ...
A274090 2017-12-31       -1,458,563,000      3,043,205,000      NaN
        2018-12-31      -15,248,690,000      2,033,330,000      NaN
A294140 2014-12-31      -10,333,092,140     20,706,250,000      NaN
        2015-12-31      -16,785,322,570     20,706,250,000      NaN
        2016-12-31      -27,958,314,430     20,706,250,000      NaN
        2017-12-31      -19,277,339,000     20,706,250,000      NaN
        2018-12-31      -10,448,308,000     15,200,000,000      NaN
A294630 2014-12-31       -8,450,753,000      3,187,110,000      NaN
        2015-12-31      -13,921,485,000      3,187,110,000      NaN
        2016-12-31      -34,199,005,000      3,213,425,000      NaN
        2017-12-31      -41,111,898,000      6,880,080,000      NaN
        2018-12-31      -42,575,729,000      7,780,080,000      NaN
A900050 2014-12-31      266,336,020,000    150,112,282,000    2,401
        2015-12-31      196,138,671,000    181,787,099,000    2,025
        2016-12-31      -32,141,967,000    284,851,043,000    1,280
A900090 2014-12-31      142,510,165,000     70,115,827,000    2,234
        2015-12-31      163,241,816,000     71,429,287,000    1,690
        2016-12-31      178,344,034,000     68,545,213,000    1,096
        2017-12-31       69,859,539,000     86,173,700,000      679
        2018-12-31                  NaN                NaN       27
A900130 2014-12-31       -9,806,136,000     30,826,855,000      860
        2015-12-31      -14,542,400,000     31,404,325,000      968
        2016-12-31      -15,709,484,000     30,136,325,000    1,370
        2017-12-31       32,635,247,000     28,464,790,000      NaN
        2018-12-31       37,153,876,000     28,309,986,000      NaN
A900180 2014-12-31      183,427,577,000     80,138,060,000    2,746
        2015-12-31      222,517,743,000     81,639,264,000    2,073
        2016-12-31      235,363,646,000    105,419,524,000    1,046
        2017-12-31      241,292,290,000     99,572,349,000      458
A950010 2014-12-31      -52,648,918,000     22,356,718,000      690

Item Name                      지배주주순이익                 총부채  \
Symbol  date
A005930 2014-12-31  23,082,499,000,000  62,334,770,000,000
        2015-12-31  18,694,628,000,000  63,119,716,000,000
        2016-12-31  22,415,655,000,000  69,211,291,000,000
        2017-12-31  41,344,569,000,000  87,260,662,000,000
        2018-12-31  43,890,877,000,000  91,604,067,000,000
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A000660 2014-12-31   4,195,456,000,000   8,846,975,000,000
        2015-12-31   4,322,356,000,000   8,290,203,000,000
        2016-12-31   2,953,774,000,000   8,192,496,000,000
        2017-12-31  10,641,512,000,000  11,597,545,000,000
        2018-12-31  15,540,111,000,000  16,806,004,000,000
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A207940 2014-12-31     -81,891,809,260     695,181,201,490
        2015-12-31   1,904,945,916,600   3,185,659,557,940
        2016-12-31    -176,823,409,530   3,450,636,646,770
        2017-12-31     -96,972,115,810   3,206,640,270,220
        2018-12-31     224,109,194,870   1,824,940,197,150
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A035420 2014-12-31     454,457,462,000   1,597,039,679,000
        2015-12-31     518,746,486,540   2,116,334,498,630
        2016-12-31     749,305,674,070   2,241,036,317,650
        2017-12-31     772,879,579,920   2,714,065,324,970
        2018-12-31     648,812,902,730   3,932,050,396,030
        2019-12-31                 NaN                 NaN
        2020-01-28                 NaN                 NaN
A005380 2014-12-31   7,346,807,000,000  84,604,552,000,000
        2015-12-31   6,417,303,000,000  98,486,545,000,000
...                                ...                 ...
A274090 2017-12-31      -1,212,973,000      15,342,229,000
        2018-12-31      -9,474,487,000      69,815,346,000
A294140 2014-12-31      -6,345,484,260       5,997,069,860
        2015-12-31      -6,452,230,430      11,430,295,710
        2016-12-31     -11,172,991,850      15,823,165,230
        2017-12-31       8,680,975,220      14,736,016,940
        2018-12-31      -2,377,218,650      10,140,606,070
A294630 2014-12-31      -1,644,225,000       9,005,440,000
        2015-12-31      -5,470,731,000      10,418,161,000
        2016-12-31     -11,741,565,000      12,225,849,000
        2017-12-31      -6,856,047,000       3,581,152,520
        2018-12-31      -1,449,384,000       3,541,386,780
A900050 2014-12-31     -93,740,159,000      51,128,152,000
        2015-12-31     -83,519,335,000     165,421,289,000
        2016-12-31    -226,170,122,000     244,246,970,000
A900090 2014-12-31      15,844,086,000     195,543,696,000
        2015-12-31      18,013,029,000     149,106,203,000
        2016-12-31      21,836,108,000     146,888,348,000
        2017-12-31    -100,887,876,000      84,130,936,000
        2018-12-31                 NaN                 NaN
A900130 2014-12-31     -10,088,316,000     210,457,789,000
        2015-12-31      -4,540,213,000     234,855,107,000
        2016-12-31      -1,765,800,000     219,073,756,000
        2017-12-31      20,626,718,000     193,961,744,000
        2018-12-31       2,671,718,000     189,321,455,000
A900180 2014-12-31      36,808,460,000     143,552,628,000
        2015-12-31      35,557,306,000     186,504,769,000
        2016-12-31      21,974,057,000     142,815,690,000
        2017-12-31      18,959,807,000     149,579,166,000
A950010 2014-12-31    -111,254,237,000     201,473,594,000

Item Name                           총자본         투자활동으로인한현금흐름
Symbol  date
A005930 2014-12-31  168,088,188,000,000  -32,806,408,000,000
        2015-12-31  179,059,805,000,000  -27,167,787,000,000
        2016-12-31  192,963,033,000,000  -29,658,675,000,000
        2017-12-31  214,491,428,000,000  -49,385,216,000,000
        2018-12-31  247,753,177,000,000  -52,240,453,000,000
        2019-12-31                  NaN                  NaN
        2020-01-28                  NaN                  NaN
A000660 2014-12-31   18,036,303,000,000   -6,087,827,000,000
        2015-12-31   21,387,703,000,000   -7,125,530,000,000
        2016-12-31   24,023,530,000,000   -6,230,451,000,000
        2017-12-31   33,820,919,000,000  -11,919,162,000,000
        2018-12-31   46,852,331,000,000  -21,428,749,000,000
        2019-12-31                  NaN                  NaN
        2020-01-28                  NaN                  NaN
A207940 2014-12-31      662,114,006,490     -526,469,029,450
        2015-12-31    2,774,834,158,510     -429,481,515,370
        2016-12-31    4,082,379,459,570   -1,372,824,475,920
        2017-12-31    3,976,450,892,360      265,185,302,990
        2018-12-31    4,155,468,451,150     -631,989,919,160
        2019-12-31                  NaN                  NaN
        2020-01-28                  NaN                  NaN
A035420 2014-12-31    1,797,418,215,000     -436,149,624,000
        2015-12-31    2,269,578,519,490     -785,858,502,000
        2016-12-31    4,129,598,862,940     -941,712,567,000
        2017-12-31    5,305,186,234,950   -1,310,331,331,650
        2018-12-31    5,949,140,513,290     -388,286,947,220
        2019-12-31                  NaN                  NaN
        2020-01-28                  NaN                  NaN
A005380 2014-12-31   62,620,565,000,000   -6,195,010,000,000
        2015-12-31   66,881,401,000,000   -8,060,288,000,000
...                                 ...                  ...
A274090 2017-12-31       15,194,858,000      -13,278,286,000
        2018-12-31      -11,419,944,000       -5,716,273,000
A294140 2014-12-31       10,373,157,860       -8,703,178,940
        2015-12-31        3,920,927,430          -13,985,590
        2016-12-31       -7,252,064,430           38,421,820
        2017-12-31        1,428,911,000         -281,712,150
        2018-12-31       26,031,297,000      -15,955,944,560
A294630 2014-12-31       14,191,726,000       -5,766,293,000
        2015-12-31        8,720,995,000       -3,714,033,000
        2016-12-31       -1,735,627,000       -2,413,311,630
        2017-12-31        4,919,091,980         -690,752,520
        2018-12-31        7,131,342,370         -368,936,630
A900050 2014-12-31      450,017,688,000      -59,099,133,000
        2015-12-31      393,734,014,000           14,827,000
        2016-12-31      250,229,345,000     -200,273,682,000
A900090 2014-12-31      216,543,388,000      -36,921,044,000
        2015-12-31      241,210,310,000      -10,712,053,000
        2016-12-31      256,135,586,000        1,382,108,000
        2017-12-31      157,907,964,000        6,911,220,000
        2018-12-31                  NaN                  NaN
A900130 2014-12-31       21,020,719,000      -19,312,399,000
        2015-12-31       16,861,926,000       -7,462,673,000
        2016-12-31       14,426,840,000       -8,959,448,000
        2017-12-31       61,076,307,000       -7,197,818,000
        2018-12-31       65,463,862,000       -6,077,621,000
A900180 2014-12-31      265,772,668,000      -67,405,318,000
        2015-12-31      308,712,215,000      -41,673,397,000
        2016-12-31      344,047,609,000      -25,311,995,000
        2017-12-31      325,189,353,000      -19,725,383,000
A950010 2014-12-31      506,680,091,000      -47,871,786,000

[15192 rows x 12 columns]

### df type 실수로 변환

In [143]:
for 계정 in df.columns:
    df[계정] = df[계정].str.replace(',', "")

df = df.astype(float)

### 생성하는 지표

In [144]:
df["시가총액"] = df["주가"] * df["상장주식수"]

In [145]:
df["ROE"] = df["지배주주순이익"] /  df["총자본"]

# 필터링 조건들을 생성한다

In [146]:
company_list = df.index.levels[0]

In [149]:
new_data = []
for company in company_list:
    temp = df.loc[company]
    
    ## 포괄손익계산서
    # 매출액 100억이상
    temp["매출액 100억 이상"] = temp["매출액"] > 10000000000
    
    #영업이익 3개년 모두 0 이상
    temp["영업이익 0 이상"] = temp["영업이익"] > 0 
    temp["영업이익 1년전 0 이상"] = temp["영업이익"].shift(1) > 0 
    temp["영업이익 2년전 0 이상"] = temp["영업이익"].shift(2) > 0 
    temp["영업이익 3년동안 0 이상"] = (temp["영업이익 0 이상"] > 0) & (temp["영업이익 1년전 0 이상"] > 0) & (temp["영업이익 2년전 0 이상"] > 0)
    
    # 매출액 3년 동안 증가
    
    temp["매출액이 과거 1년&2년전 보다 크다"] = (temp["매출액"] > temp["매출액"].shift(1)) & (temp["매출액"] > temp["매출액"].shift(2))
    temp["과거 1년전 매출액이 2년전 매출액보다 크다"] = temp["매출액"].shift(1) > temp["매출액"].shift(2)
    temp["매출액 3년동안 증가"] = temp["매출액이 과거 1년&2년전 보다 크다"] & temp["과거 1년전 매출액이 2년전 매출액보다 크다"]    
    
    # 시가총액 비율
    temp["순이익시총비율 0.1이상"] = (temp["지배주주순이익"] / temp["시가총액"])  > 0.1
    temp["영업이익시총비율 0.1이상"] = (temp["영업이익"] / temp["시가총액"]) > 0.1
    
    
    
    ## 재무상태표
    # 자본잠식
    temp["자본잠식 없음"] = temp["총자본"] > 0
    
    # 부채비율
    temp["부채비율"] = temp["총부채"] / temp["총자본"]
    temp["부채비율 150% 이하"] = temp["부채비율"] < 1.5
    temp["부채비율 감소추세"] = (temp["부채비율"] < temp["부채비율"].shift(1)) & (temp["부채비율"] < temp["부채비율"].shift(2))
    
    # 자본금
    temp["자본금 증가율"] = (temp["자본금"] - temp["자본금"].shift(1)) / temp["자본금"].shift(1)
    temp["자본금 변동없음"] = temp["자본금 증가율"].abs() < 0.05
    
    # 이익잉여금
    temp["이익잉여금이 과거 1년&2년전 보다 크다"] = (temp["이익잉여금"] > temp["이익잉여금"].shift(1)) & (temp["이익잉여금"] > temp["이익잉여금"].shift(2))
    temp["과거 1년전 이익잉여금이 2년전 이익잉여금보다 크다"] = temp["이익잉여금"].shift(1) > temp["이익잉여금"].shift(2)
    temp["이익잉여금이 3년동안 증가"] = temp["이익잉여금이 과거 1년&2년전 보다 크다"] & temp["과거 1년전 이익잉여금이 2년전 이익잉여금보다 크다"]

    
    ## 현금흐름표
    
    temp["영업활동으로인한현금흐름 판별"] = temp["영업활동으로인한현금흐름"] > 0
    temp["3년 중 2년 이상 영업활동으로인한현금흐름 0 이상"] = (temp["영업활동으로인한현금흐름 판별"].rolling(3).sum() > 2)
    
    ## 배당
    temp["배당존재"] = temp["배당"] > 0 
    temp["배당이 과거 1년&2년전 보다 크다"] = (temp["배당"] > temp["배당"].shift(1)) & (temp["배당"] > temp["배당"].shift(2))
    temp["과거 1년전 배당이 2년전 배당보다 크다"] = temp["배당"].shift(1) > temp["배당"].shift(2)
    temp["배당이 3년동안 증가"] = temp["배당이 과거 1년&2년전 보다 크다"] & temp["과거 1년전 배당이 2년전 배당보다 크다"]
    
    
    ## 기타
    
    # ROE가 5% 이상
    temp["ROE 5퍼 이상"]  = temp["ROE"] > 0.05
    
    
    temp["Symbol"] = company
    temp = temp.reset_index()
    temp = temp.set_index(["Symbol", "date"])
    
    new_data.append(temp)

In [150]:
old = pd.DataFrame()
for company_data in new_data:
    old = pd.concat([old, company_data])

In [151]:
필터조건 = ["매출액 100억 이상", "영업이익 3년동안 0 이상", "매출액 3년동안 증가", "순이익시총비율 0.1이상", 
        "영업이익시총비율 0.1이상","자본잠식 없음", "부채비율 150% 이하", "부채비율 감소추세", "자본금 변동없음", 
        "이익잉여금이 3년동안 증가","3년 중 2년 이상 영업활동으로인한현금흐름 0 이상", "배당존재", "배당이 3년동안 증가",
       "ROE 5퍼 이상"]

In [152]:
년도별조건 = old[필터조건]

In [153]:
년도별조건.to_csv("year_filter.csv", encoding = "ms949")