In [1]:
import pandas as pd
from dateutil.relativedelta import relativedelta

### 데이터 로드

In [2]:
df = pd.read_csv("..\\..\\data\\donghyojaechul_yearly_financial_5years.csv", encoding = "ms949")

### 데이터의 계정이름을 사용하기 쉬운 계정이름으로 변환

In [3]:
계정명 = df["Item Name "].drop_duplicates().tolist()

In [4]:
바꿀계정명 = ["매출액", "영업이익", "지배주주순이익", "총자본", "총부채", "자본금", "이익잉여금", 
                 "영업활동으로인한현금흐름", "투자활동으로인한현금흐름", "배당", "주가", "상장주식수"]

In [5]:
temp = {}

for 계정 in range(len(계정명)):
    temp[계정명[계정]] = 바꿀계정명[계정]
    print(계정명[계정]+ "     ->     " +  바꿀계정명[계정])

매출액(원)     ->     매출액
영업이익(원)     ->     영업이익
지배주주순이익(원)     ->     지배주주순이익
총자본(원)     ->     총자본
총부채(원)     ->     총부채
자본금(원)     ->     자본금
이익잉여금(원)     ->     이익잉여금
영업활동으로인한현금흐름(원)     ->     영업활동으로인한현금흐름
투자활동으로인한현금흐름(원)     ->     투자활동으로인한현금흐름
수정DPS(보통주,현금)(원)     ->     배당
수정주가(원)     ->     주가
상장주식수 (보통+우선)(주)     ->     상장주식수

### 바뀐 계정 할당

In [6]:
df = df.replace({"Item Name ": temp})

### 인덱스를 회사 - 시간의 이중 인덱스 변경. 컬럼은 재무 지표들로 변경

In [7]:
df = df.set_index(['Symbol', "Item Name "])
시간변환 = pd.to_datetime(df.columns)

시간변환 = 시간변환.strftime("%Y-%m-%d")
시간변환 = 시간변환.rename("date")
df.columns = pd.to_datetime(시간변환)
df = df.stack().swaplevel().unstack()

In [8]:
df.head()

Item Name                           매출액        배당          상장주식수  \
Symbol  date
A005930 2014-12-31  137,825,547,000,000    400.00    170,132,764
        2015-12-31  135,205,045,000,000    420.00    170,132,764
        2016-12-31  133,947,204,000,000    570.00    161,192,764
        2017-12-31  161,915,007,000,000    850.00    147,349,074
        2018-12-31  170,381,870,000,000  1,416.00  6,792,669,250

Item Name                         영업이익        영업활동으로인한현금흐름  \
Symbol  date
A005930 2014-12-31  25,025,071,000,000  36,975,389,000,000
        2015-12-31  26,413,442,000,000  40,061,761,000,000
        2016-12-31  29,240,672,000,000  47,385,644,000,000
        2017-12-31  53,645,038,000,000  62,162,041,000,000
        2018-12-31  58,886,669,000,000  67,031,863,000,000

Item Name                         이익잉여금              자본금      주가  \
Symbol  date
A005930 2014-12-31  169,529,604,000,000  897,514,000,000  26,540
        2015-12-31  185,132,014,000,000  897,514,000,000  25,200
        2016-12-31  193,086,317,000,000  897,514,000,000  36,040
        2017-12-31  215,811,200,000,000  897,514,000,000  50,960
        2018-12-31  242,698,956,000,000  897,514,000,000  38,700

Item Name                      지배주주순이익                 총부채  \
Symbol  date
A005930 2014-12-31  23,082,499,000,000  62,334,770,000,000
        2015-12-31  18,694,628,000,000  63,119,716,000,000
        2016-12-31  22,415,655,000,000  69,211,291,000,000
        2017-12-31  41,344,569,000,000  87,260,662,000,000
        2018-12-31  43,890,877,000,000  91,604,067,000,000

Item Name                           총자본         투자활동으로인한현금흐름
Symbol  date
A005930 2014-12-31  168,088,188,000,000  -32,806,408,000,000
        2015-12-31  179,059,805,000,000  -27,167,787,000,000
        2016-12-31  192,963,033,000,000  -29,658,675,000,000
        2017-12-31  214,491,428,000,000  -49,385,216,000,000
        2018-12-31  247,753,177,000,000  -52,240,453,000,000

### df type 실수로 변환

In [9]:
for 계정 in df.columns:
    df[계정] = df[계정].str.replace(',', "")

df = df.astype(float)

In [10]:
# 데이터들의 년도를 미뤄주는 함수. 예를 들어 lag_year가 1년이면 1년전의 데이터를 가져오겠다는 뜻!! 한번 실행해보길
def lag_year(df, lag_year):
    copy_df = df.copy()
    lagged_df = copy_df.shift(lag_year)
    lag_index_list = []
    for index in df.columns:
        lag_index = index + " " + str(lag_year) + "Y lag"
        lag_index_list.append(lag_index)
    
    lagged_df.columns = lag_index_list
    
    return lagged_df

In [11]:
# 3월 15일을 기준으로 사용할 수 있는 재무데이터의 년도가 다름. 3월 전에는 전전년도의 재무데이터를 사용가능하지만
# 4월부터는 전년도 재무데이터를 사용할 수 있음
# 마찬가지로 이해가 안 된다면 실행시켜보길 권함!

def assign_announcement_year(df):
    copy_df = df.copy()
    
    for time in reversed(copy_df.index):

        month = time.month
        day = time.day
        
        try:

            if month > 3:
                
                ref_time = time- relativedelta(years = 1) # 작년 12월 데이터를 카피한다
                copy_df.loc[time] = copy_df.loc[ref_time]

                
            else:
                ref_time = time- relativedelta(years = 1) - relativedelta(months = month-1) - relativedelta(days = day) 
                copy_df.loc[time] = copy_df.loc[ref_time]                

        except Exception as e:
            copy_df.loc[time] = None
            pass
    
    return copy_df

### 시가총액과 ROE 생성

In [12]:
df["시가총액"] = df["주가"] * df["상장주식수"]
df["ROE"] = df["지배주주순이익"] /  df["총자본"]

In [13]:
company = 'A005930'
## 이 부분이 복잡해보이는데 복사해서 밖으로 빼서 별도의 셀에서 한 행씩 실행시켜보면 이해가 됨

 # 회사의 데이터를 가져와서
temp = df.loc[company] 
# 즉시 알 수 있는 주식 데이터들만을 뽑아온 후
stock_data = df.loc[company][["주가", "상장주식수", "시가총액"]]
# 전년도에 대한 감사보고서 제출일이 3월 15일 이므로 3월을 기준으로 이전이라면 2년전의 데이터, 이후라면 1년전의 데이터 사용
temp = assign_announcement_year(temp)
# 필터 조건을 위한 전년도 데이터들을 생성하고
lag_1Y = lag_year(temp, 1)
lag_2Y = lag_year(temp, 2)
lag_3Y = lag_year(temp, 3)
lag_4Y = lag_year(temp, 4)
# 이를 합친다
temp = pd.concat([temp, lag_1Y, lag_2Y, lag_3Y, lag_4Y], axis = 1)

# 즉시 알 수 있는 stock data들도 재무데이터들과 마찬가지로 미뤄졌으므로, 다시 원래 데이터를 할당한다
temp[stock_data.columns]= stock_data

# temp를 밖에서 빼서 한번씩 실행하면 이해가 될거임!

In [14]:
temp

,매출액,배당,상장주식수,영업이익,영업활동으로인한현금흐름,이익잉여금,자본금,주가,지배주주순이익,총부채,...,영업활동으로인한현금흐름 4Y lag,이익잉여금 4Y lag,자본금 4Y lag,주가 4Y lag,지배주주순이익 4Y lag,총부채 4Y lag,총자본 4Y lag,투자활동으로인한현금흐름 4Y lag,시가총액 4Y lag,ROE 4Y lag
date,,,,,,,,,,,,,,,,,,,,,
2014-12-31,NaN,NaN,1.701328e+08,NaN,NaN,NaN,NaN,26540.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-31,1.378255e+14,400.0,1.701328e+08,2.502507e+13,3.697539e+13,1.695296e+14,8.975140e+11,25200.0,2.308250e+13,6.233477e+13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-12-31,1.352050e+14,420.0,1.611928e+08,2.641344e+13,4.006176e+13,1.851320e+14,8.975140e+11,36040.0,1.869463e+13,6.311972e+13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-31,1.339472e+14,570.0,1.473491e+08,2.924067e+13,4.738564e+13,1.930863e+14,8.975140e+11,50960.0,2.241566e+13,6.921129e+13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-12-31,1.619150e+14,850.0,6.792669e+09,5.364504e+13,6.216204e+13,2.158112e+14,8.975140e+11,38700.0,4.134457e+13,8.726066e+13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-31,1.703819e+14,1416.0,6.792669e+09,5.888667e+13,6.703186e+13,2.426990e+14,8.975140e+11,55800.0,4.389088e+13,9.160407e+13,...,3.697539e+13,1.695296e+14,8.975140e+11,26540.0,2.308250e+13,6.233477e+13,1.680882e+14,-3.280641e+13,4.515324e+12,0.137324
2020-01-28,1.703819e+14,1416.0,6.792669e+09,5.888667e+13,6.703186e+13,2.426990e+14,8.975140e+11,58800.0,4.389088e+13,9.160407e+13,...,4.006176e+13,1.851320e+14,8.975140e+11,25200.0,1.869463e+13,6.311972e+13,1.790598e+14,-2.716779e+13,4.287346e+12,0.104404

In [15]:
# temp의 모양을 살펴보면 위와 같음.
# 즉 아래함수의 윗 부분은 해당 시점에 알 수 있는 가장 최신 데이터들로 바꿔주는 역할을 해줌

## 필터링 조건 생성부

In [16]:
company_list = df.index.levels[0]

In [21]:
new_data = []
for company in company_list:
    ## 이 부분이 복잡해보이는데 복사해서 밖으로 빼서 별도의 셀에서 한 행씩 실행시켜보면 이해가 됨
    
     # 회사의 데이터를 가져와서
    temp = df.loc[company] 
    # 즉시 알 수 있는 주식 데이터들만을 뽑아온 후
    stock_data = df.loc[company][["주가", "상장주식수", "시가총액"]]
    # 전년도에 대한 감사보고서 제출일이 3월 15일 이므로 3월을 기준으로 이전이라면 2년전의 데이터, 이후라면 1년전의 데이터 사용
    temp = assign_announcement_year(temp)
    # 필터 조건을 위한 전년도 데이터들을 생성하고
    lag_1Y = lag_year(temp, 1)
    lag_2Y = lag_year(temp, 2)
    lag_3Y = lag_year(temp, 3)
    lag_4Y = lag_year(temp, 4)
    # 이를 합친다
    temp = pd.concat([temp, lag_1Y, lag_2Y, lag_3Y, lag_4Y], axis = 1)
    
    # 즉시 알 수 있는 stock data들도 재무데이터들과 마찬가지로 미뤄졌으므로, 다시 원래 데이터를 할당한다
    temp[stock_data.columns]= stock_data
    
    # temp를 밖에서 빼서 한번씩 실행하면 이해가 될거임!
    

    # 2020년 2월 현재 알 수 있는 회사들의 재무데이터는 2019년 데이터가 아닌 2018년 데이터이다.
    # 2019년의 감사보고서의 제출 마감일은 2019년 3월 15일 까지로, 넉넉잡아 2019년 4월 1일부터는 감사보고서의
    # 데이터들을 사용할 수 있다.
    
    # 즉 정리하자면 2020년 2월 현재 회사에 대한 가장 최근 재무데이터들은 2018년 데이터들이고, 2019년 데이터가 아니다.
    # 2020년 4월이 된다면 활용할 수 있는 가장 최근 재무데이터들은 2019년 데이터이다.
    # 4월을 기점으로 이러한 시간의 변동이 일어나게 된다.
    

    
    ## 포괄손익계산서
    # 매출액 100억이상
    temp["매출액 100억 이상"] = temp["매출액"] > 10000000000
    
    #영업이익 3개년 모두 0 이상
    temp["영업이익 3년동안 0 이상"] = (temp["영업이익"] > 0) & (temp["영업이익 1Y lag"] > 0) & (temp["영업이익 2Y lag"] > 0)
  
    # 매출액 3년 동안 증가
    
    temp["매출액 3년동안 증가"] = (temp["매출액"] > temp["매출액 1Y lag"]) &  (temp["매출액"] > temp["매출액 2Y lag"]) &  (temp["매출액 1Y lag"] > temp["매출액 2Y lag"])
    
  
    # 시가총액 비율
    temp["순이익시총비율 0.1이상"] = (temp["지배주주순이익"] / temp["시가총액"])  > 0.1
    temp["영업이익시총비율 0.1이상"] = (temp["영업이익"] / temp["시가총액"]) > 0.1
    
    
    
    ## 재무상태표
    # 자본잠식
    temp["자본잠식 없음"] = temp["총자본"] > 0
    
    # 부채비율
    temp["부채비율"] = temp["총부채"] / temp["총자본"]
    temp["부채비율 150% 이하"] = temp["부채비율"] < 1.5
  
    # 자본금
    temp["자본금 증가율"] = (temp["자본금"] - temp["자본금 1Y lag"]) / temp["자본금 1Y lag"]
    temp["자본금 변동없음"] = temp["자본금 증가율"].abs() < 0.05
    
    # 이익잉여금
    
    temp["이익잉여금이 3년동안 증가"] = (temp["이익잉여금"] > temp["이익잉여금 1Y lag"]) &  (temp["이익잉여금"] > temp["이익잉여금 2Y lag"]) &  (temp["이익잉여금 1Y lag"] > temp["이익잉여금 2Y lag"])

    
    ## 현금흐름표
    
    # 영업활동현금흐름
    temp["영업활동으로인한현금흐름 판별"] = temp["영업활동으로인한현금흐름"] > 0
    temp["3년 중 2년 이상 영업활동으로인한현금흐름 0 초과"] = (temp["영업활동으로인한현금흐름 판별"].rolling(3).sum() > 2)
    
    # 투자활동현금흐름

    temp["투자활동으로인한현금흐름 판별"] = temp["투자활동으로인한현금흐름"] < 0
    temp["3년 중 2년 이상 투자활동으로인한현금흐름 0 미만"] = (temp["투자활동으로인한현금흐름 판별"].rolling(3).sum() > 2)
    
    
    ## 배당
    temp["배당존재"] = temp["배당"] > 0 
    temp["배당이 3년동안 증가"] =(temp["배당"] > temp["배당 1Y lag"]) &  (temp["배당"] > temp["배당 2Y lag"]) &  (temp["배당 1Y lag"] > temp["배당 2Y lag"])

    
    ## 기타
    
    # ROE가 5% 이상
    temp["ROE 5퍼 이상"]  = temp["ROE"] > 0.05
    
    # 추후 많은 지표들 추가
    
    
    temp["Symbol"] = company
    temp = temp.reset_index()
    temp = temp.set_index(["Symbol", "date"])
    
    new_data.append(temp)

In [22]:
old = pd.DataFrame()
for company_data in new_data:
    old = pd.concat([old, company_data])

In [23]:
필터조건 = ["매출액 100억 이상", "영업이익 3년동안 0 이상", "매출액 3년동안 증가", "순이익시총비율 0.1이상", 
        "영업이익시총비율 0.1이상","자본잠식 없음", "부채비율 150% 이하", "자본금 변동없음", 
        "이익잉여금이 3년동안 증가","3년 중 2년 이상 영업활동으로인한현금흐름 0 초과",
        "3년 중 2년 이상 투자활동으로인한현금흐름 0 미만","배당존재", "배당이 3년동안 증가","ROE 5퍼 이상"]

In [24]:
년도별조건 = old[필터조건]

In [25]:
년도별조건

                    매출액 100억 이상  영업이익 3년동안 0 이상  매출액 3년동안 증가  순이익시총비율 0.1이상  \
Symbol  date
A005930 2014-12-31        False           False        False          False
        2015-12-31         True           False        False           True
        2016-12-31         True           False        False           True
        2017-12-31         True            True        False           True
        2018-12-31         True            True        False           True
        2019-12-31         True            True         True           True
        2020-01-28         True            True        False           True
A000660 2014-12-31        False           False        False          False
        2015-12-31         True           False        False           True
        2016-12-31         True           False        False           True
        2017-12-31         True            True        False          False
        2018-12-31         True            True        False           True
        2019-12-31         True            True         True           True
        2020-01-28         True            True        False           True
A207940 2014-12-31        False           False        False          False
        2015-12-31         True           False        False          False
        2016-12-31         True           False        False           True
        2017-12-31         True           False        False          False
        2018-12-31         True           False         True          False
        2019-12-31         True           False         True          False
        2020-01-28         True            True        False          False
A035420 2014-12-31        False           False        False          False
        2015-12-31         True           False        False           True
        2016-12-31         True           False        False           True
        2017-12-31         True            True         True           True
        2018-12-31         True            True         True          False
        2019-12-31         True            True         True          False
        2020-01-28         True            True        False          False
A005380 2014-12-31        False           False        False          False
        2015-12-31         True           False        False           True
...                         ...             ...          ...            ...
A274090 2017-12-31        False           False        False          False
        2018-12-31        False           False        False          False
A294140 2014-12-31        False           False        False          False
        2015-12-31        False           False        False          False
        2016-12-31        False           False        False          False
        2017-12-31        False           False         True          False
        2018-12-31         True           False         True          False
A294630 2014-12-31        False           False        False          False
        2015-12-31        False           False        False          False
        2016-12-31        False           False        False          False
        2017-12-31        False           False        False          False
        2018-12-31        False           False        False          False
A900050 2014-12-31        False           False        False          False
        2015-12-31        False           False        False          False
        2016-12-31        False           False        False          False
A900090 2014-12-31        False           False        False          False
        2015-12-31        False           False        False           True
        2016-12-31        False           False        False           True
        2017-12-31        False            True        False           True
        2018-12-31        False           False        False          False
A900130 2014-12-31        False           False        False          False
        2015-12-31        False           False        False          False
        2016-12-31        False           False        False          False
        2017-12-31        False           False        False          False
        2018-12-31        False           False        False          False
A900180 2014-12-31        False           False        False          False
        2015-12-31        False           False        False           True
        2016-12-31        False           False        False           True
        2017-12-31        False            True        False           True
A950010 2014-12-31        False           False        False          False

                    영업이익시총비율 0.1이상  자본잠식 없음  부채비율 150% 이하  자본금 변동없음  \
Symbol  date
A005930 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
        2016-12-31            True     True          True      True
        2017-12-31            True     True          True      True
        2018-12-31            True     True          True      True
        2019-12-31            True     True          True      True
        2020-01-28            True     True          True      True
A000660 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
        2016-12-31            True     True          True      True
        2017-12-31           False     True          True      True
        2018-12-31            True     True          True      True
        2019-12-31            True     True          True      True
        2020-01-28            True     True          True      True
A207940 2014-12-31           False    False         False     False
        2015-12-31           False     True          True     False
        2016-12-31           False     True          True     False
        2017-12-31           False     True          True     False
        2018-12-31           False     True          True      True
        2019-12-31           False     True          True      True
        2020-01-28           False     True          True      True
A035420 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
        2016-12-31            True     True          True      True
        2017-12-31            True     True          True      True
        2018-12-31           False     True          True      True
        2019-12-31           False     True          True      True
        2020-01-28           False     True          True      True
A005380 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
...                            ...      ...           ...       ...
A274090 2017-12-31           False     True         False     False
        2018-12-31           False     True          True     False
A294140 2014-12-31           False    False         False     False
        2015-12-31           False     True          True     False
        2016-12-31           False     True         False      True
        2017-12-31           False    False          True      True
        2018-12-31           False     True         False      True
A294630 2014-12-31           False    False         False     False
        2015-12-31           False     True          True     False
        2016-12-31           False     True          True      True
        2017-12-31           False    False          True      True
        2018-12-31           False     True          True     False
A900050 2014-12-31           False    False         False     False
        2015-12-31           False     True          True     False
        2016-12-31           False     True          True     False
A900090 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
        2016-12-31            True     True          True      True
        2017-12-31            True     True          True      True
        2018-12-31           False     True          True     False
A900130 2014-12-31           False    False         False     False
        2015-12-31           False     True         False     False
        2016-12-31           False     True         False      True
        2017-12-31           False     True         False      True
        2018-12-31           False     True         False     False
A900180 2014-12-31           False    False         False     False
        2015-12-31            True     True          True     False
        2016-12-31            True     True          True      True
        2017-12-31            True     True          True     False
A950010 2014-12-31           False    False         False     False

                    이익잉여금이 3년동안 증가  3년 중 2년 이상 영업활동으로인한현금흐름 0 초과  \
Symbol  date
A005930 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31            True                          True
        2018-12-31            True                          True
        2019-12-31            True                          True
        2020-01-28           False                          True
A000660 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31            True                          True
        2018-12-31            True                          True
        2019-12-31            True                          True
        2020-01-28           False                          True
A207940 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31           False                         False
        2018-12-31           False                         False
        2019-12-31           False                         False
        2020-01-28           False                         False
A035420 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31            True                          True
        2018-12-31            True                          True
        2019-12-31            True                          True
        2020-01-28           False                          True
A005380 2014-12-31           False                         False
        2015-12-31           False                         False
...                            ...                           ...
A274090 2017-12-31           False                         False
        2018-12-31           False                         False
A294140 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31           False                         False
        2018-12-31           False                         False
A294630 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31           False                         False
        2018-12-31           False                         False
A900050 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
A900090 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31            True                         False
        2018-12-31           False                          True
A900130 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31           False                          True
        2018-12-31           False                          True
A900180 2014-12-31           False                         False
        2015-12-31           False                         False
        2016-12-31           False                         False
        2017-12-31            True                          True
A950010 2014-12-31           False                         False

                    3년 중 2년 이상 투자활동으로인한현금흐름 0 미만   배당존재  배당이 3년동안 증가  \
Symbol  date
A005930 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-28                          True   True        False
A000660 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-28                          True   True        False
A207940 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                         False  False        False
        2019-12-31                         False  False        False
        2020-01-28                         False  False        False
A035420 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
        2016-12-31                         False   True        False
        2017-12-31                          True   True         True
        2018-12-31                          True   True         True
        2019-12-31                          True   True         True
        2020-01-28                          True   True        False
A005380 2014-12-31                         False  False        False
        2015-12-31                         False   True        False
...                                          ...    ...          ...
A274090 2017-12-31                         False  False        False
        2018-12-31                          True  False        False
A294140 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                         False  False        False
        2018-12-31                         False  False        False
A294630 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                          True  False        False
A900050 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
A900090 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                         False  False        False
        2018-12-31                         False  False        False
A900130 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
        2018-12-31                          True  False        False
A900180 2014-12-31                         False  False        False
        2015-12-31                         False  False        False
        2016-12-31                         False  False        False
        2017-12-31                          True  False        False
A950010 2014-12-31                         False  False        False

                    ROE 5퍼 이상
Symbol  date
A005930 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-28       True
A000660 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-28       True
A207940 2014-12-31      False
        2015-12-31      False
        2016-12-31       True
        2017-12-31      False
        2018-12-31      False
        2019-12-31       True
        2020-01-28       True
A035420 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31       True
        2019-12-31       True
        2020-01-28       True
A005380 2014-12-31      False
        2015-12-31       True
...                       ...
A274090 2017-12-31      False
        2018-12-31      False
A294140 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31       True
        2018-12-31       True
A294630 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31       True
        2018-12-31      False
A900050 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
A900090 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
        2018-12-31      False
A900130 2014-12-31      False
        2015-12-31      False
        2016-12-31      False
        2017-12-31      False
        2018-12-31       True
A900180 2014-12-31      False
        2015-12-31       True
        2016-12-31       True
        2017-12-31       True
A950010 2014-12-31      False

[15192 rows x 14 columns]

In [26]:
년도별조건.to_csv("year_filter.csv", encoding = "ms949")